### ISSUE TITLE
Exception after successfully uploading an archive

### ISSUE THREAD

**Issue by ckotso** [longaccess/longaccess-client#5]
Right after uploading an archive successfully (on Ubuntu 14.04):

done.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/longaccess-client/pyinstall/build/lacli/out00-PYZ.pyz/threading", line 551, in __bootstrap_inner
  File "/home/ubuntu/longaccess-client/pyinstall/build/lacli/out00-PYZ.pyz/threading", line 504, in run
  File "/home/costas/local/lib/lacli/eggs/logutils-0.3.3-py2.7.egg/logutils/queue.py", line 184, in _monitor
    record = self.dequeue(True)
  File "/home/costas/local/lib/lacli/eggs/logutils-0.3.3-py2.7.egg/logutils/queue.py", line 134, in dequeue
    return self.queue.get(block)
  File "/home/ubuntu/longaccess-client/pyinstall/build/lacli/out00-PYZ.pyz/multiprocessing.queues", line 117, in get
EOFError

**Comment by kouk** [comment]
Thanks for the report. I've encountered this myself once, somewhere in the threading library something isn't getting cleaned up. Trying to find exactly why and then I'll release a fixed version. Thanks for the feedback!
